### ISSUE TITLE
Add web pages for Cart, Delivery, Payment and Customer Care

### ISSUE THREAD

**Issue by siddhesh0533** [siddhesh0533/Ajio_clone#1]
Add web pages for Cart, Delivery, Payment and Customer Care. Make pages responsive, attractive and functional.

**Comment by kolekarmahadev20** [comment]
hi Siddhesh i can add cart, delivery, payment file

**Comment by SahilYadav9668** [comment]
hi siddhesh i can add customer care fetaure

**Comment by siddhesh0533** [comment]
The website is ready. All the web pages i wanted are made by mahadev and sahil
